spring.application.name=juice-shop
spring.datasource.url=jdbc:postgresql://localhost:5432/juice-shop
spring.datasource.username=administrator
spring.datasource.password=pass123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

spring.session.jdbc.initialize-schema=always

server.port=9090